language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_install: cp configuration.properties-sample configuration.properties
script:
 - wget http://archive.apache.org/dist/maven/binaries/apache-maven-2.2.1-bin.tar.gz
 - tar -xf apache-maven-2.2.1.bin.tar.gz
 - apache-maven-2.2.1/bin/mvn
