language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

# Patch for buffer overflow bug, see https://github.com/travis-ci/travis-ci/issues/5227
addons:
  hosts:
    - vhdllab
  hostname: vhdllab

before_install:
  - cp configuration.properties-sample configuration.properties

script:
  - ./gradlew build
