language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_install:
  # Patch for buffer overflow bug, see https://github.com/travis-ci/travis-ci/issues/5227
  - hostname
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - hostname
  - cat /etc/hosts # optionally check the content *after*
  - cp configuration.properties-sample configuration.properties

script:
  - ./gradlew build
